### ISSUE TITLE
What is the license of this bundle ? MIT or OSL-3 ?

### ISSUE THREAD

**Issue by mmondino** [oroinc/OroCalendarBundle#5]
MIT -> https://github.com/oroinc/OroCalendarBundle/blob/master/LICENSE

OSL-3 -> https://github.com/oroinc/OroCalendarBundle/blob/master/composer.json#L7

**Comment by mbessolov** [comment]
The license is MIT.
Thanks for pointing out the error in composer.json, we'll fix it.

**Comment by mbessolov** [comment]
Fixed in 944a9a7640dbb160512fbe927754bed8d3170604
